heroku_deploy:
  stage: build
  script:
    - git remote add heroku-web https://heroku:$HEROKU_PRODUCTION_KEY@git.heroku.com/$HEROKU_WEB.git
    - git remote add heroku-backend https://heroku:$HEROKU_PRODUCTION_KEY@git.heroku.com/$HEROKU_BACKEND.git
    - git push -f heroku-web HEAD:main
    - git push -f heroku-backend HEAD:main
