export const users = [
  {
    username: 'wesleylim.work@gmail.com',
    password: 'password',
    eventIds: [],
    schedule: [],
    notifications: [],
    address: null,
  },
  {
    username: 'anais.lengoc@gmail.com',
    password: 'password',
    eventIds: [],
    schedule: [],
    notifications: [],
    address: null,
  },
  {
    username: 'gpalanca10@gmail.com',
    password: 'password',
    eventIds: [],
    schedule: [],
    notifications: [],
    address: null,
  },
  {
    username: 'jeda1998@gmail.com',
    password: 'password',
    eventIds: [],
    schedule: [],
    notifications: [],
    address: null,
  },
  {
    username: 'lerlianping@hotmail.com',
    password: 'password',
    eventIds: [],
    schedule: [],
    notifications: [],
    address: null,
  },
  {
    username: 'sufyanjais1@gmail.com',
    password: 'password',
    eventIds: [],
    schedule: [],
    notifications: [],
    address: null,
  },
];
