export const NAVIGATION_HEIGHT = 45;

export const AUTH_USER_MAX_PARTICIPANTS = 10;

export const PresentablePlaceTypeMap: Record<string, string> = {
	activities: 'Activities',
	'activity.community_center': 'Community Centres',
	'activity.sport_club': 'Sport Clubs',
	commercial: 'Shopping',
	'commercial.outdoor_and_sport': 'Outdoor and sports shops',
	'commercial.shopping_mall': 'Shopping malls',
	'commercial.department_store': 'Department stores',
	'commercial.hobby': 'Hobby-related shops',
	'commercial.books': 'Book shops',
	'commercial.gift_and_souvenir': 'Gift and Souvenir shops',
	'commercial.tickets_and_lottery': 'Tickets and lottery shops',
	'commercial.clothing': 'Clothing and Bags',
	'commercial.bag': 'Clothing and Bags',
	'commercial.health_and_beauty': 'Healthy and Beauty shops',
	'commercial.food_and_drink': 'Food and Drinks',
	'commercial.art': 'Art and Antiques shops',
	'commercial.antiques': 'Art and Antiques shops',
	'commercial.video_and_music': 'Video and Music shops',
	catering: 'Food',
	'catering.restaurant': 'Restaurants',
	'catering.fast_food': 'Fast food',
	'catering.cafe': 'Cafes',
	'catering.food_court': 'Food courts',
	'catering.bar': 'Bars and Pubs',
	'catering.pub': 'Bars and Pubs',
	'catering.ice_cream': 'Ice cream',
	entertainment: 'Entertainment',
	'entertainment.culture': 'Culture',
	'entertainment.zoo': 'Zoo',
	'entertainment.aquarium': 'Entertainment',
	'entertainment.planetarium': 'Planetarium',
	'entertainment.cinema': 'Cinema',
	'entertainment.amusement_arcade': 'Arcade',
	'entertainment.escape_game': 'Escape-room',
	'entertainment.miniature_golf': 'Miniature golf',
	'entertainment.bowling_alley': 'Bowling Alley',
	'entertainment.theme_park': 'Theme park',
	'entertainment.flying_fox': 'Flying fox',
	'entertainment.water_park': 'Water park',
	leisure: 'Leisure',
	'leisure.picnic': 'Picnic',
	'leisure.picnic.bbq': 'Barbecue',
	'leisure.playground': 'Playground',
	'leisure.spa': 'Spa',
	'leisure.park': 'Park',
	natural: 'Nature',
	national_park: 'National Park',
	rental: 'Rental',
	tourism: 'Tourist spots',
	'tourism.attraction': 'Attractions',
	'tourism.sights': 'Sights',
	camping: 'Camping',
	beach: 'Beach',
	adult: 'Adult stuff',
	'adult.nightclub': 'Night club',
	'adult.stripclub': 'Strip club',
	'adult.casino': 'Casino',
	'adult.adult_gaming_centre': 'Adult Gaming Centre',
};
